version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12342'
      MYSQL_DATABASE: 'monolithsz'
      MYSQL_USER: 'usr2'
      MYSQL_PASSWORD: '12342'
    ports:
      - "7772:3306"
    volumes:
      - db_data_2:/var/lib/mysql

volumes:
  db_data_2 :